version: '3'

volumes:
  data:
  mysql:
    driver: local

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "22000:80"
    depends_on:
      - mysql
    volumes:
      - ./:/var/www/html # Mount the current directory to /var/www/html for dev purposes
    #        - data:data # Mount the data volume to /var/www/html/data for prod purposes
    env_file:
      - ./.env
    restart: always


  mysql:
    container_name: mysql
    image: mysql/mysql-server:latest-aarch64
    ports:
      - "3307:3306"
    volumes:
      - mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    tty: true